file(MAKE_DIRECTORY "${WORK_DIR}")

function(expect_cli expected_code expected_pattern)
    execute_process(COMMAND "${EXECUTABLE}" ${ARGN}
        WORKING_DIRECTORY "${WORK_DIR}"
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT "${code}" STREQUAL "${expected_code}")
        message(FATAL_ERROR "Unexpected exit code ${code}; expected ${expected_code}.\n${output}\n${error}")
    endif()
    if(NOT "${output}${error}" MATCHES "${expected_pattern}")
        message(FATAL_ERROR "Missing expected CLI diagnostic.\n${output}\n${error}")
    endif()
endfunction()

expect_cli(0 "validate" --help)
expect_cli(0 "0\\.4\\.0" --version)
expect_cli(2 "Usage error")
expect_cli(2 "Unknown command" solve)
expect_cli(2 "requires a file path" validate --config)
expect_cli(2 "requires a file path" validate --config --checkpoint x)
expect_cli(2 "Duplicate option" validate --config a --config b)
expect_cli(2 "only by resume" validate --config a --checkpoint b)
expect_cli(2 "requires --checkpoint" resume --config a)

expect_cli(3 "not implemented in stage 4" resume --config a --checkpoint b)
expect_cli(1 "Cannot open configuration" validate --config missing.json)
expect_cli(0 "vertices=9 edges=10 alpha_tasks=10" validate --config "${SOURCE_DIR}/examples/config.json")
expect_cli(0 "alpha=0\\.3 r=2" validate --config "${SOURCE_DIR}/examples/config.json")
expect_cli(0 "alpha=1 r=9" validate --config "${SOURCE_DIR}/examples/config.json")
expect_cli(0 "nodes=3 maximum_k=2" tree --config "${SOURCE_DIR}/examples/config.json")
expect_cli(0 "k=2 size=6 vertices=10,20,30,40,50,60" tree --config "${SOURCE_DIR}/examples/config.json")
expect_cli(0 "k=2 size=3 vertices=70,80,90" tree --config "${SOURCE_DIR}/examples/config.json")
expect_cli(2 "only by resume" tree --config a --checkpoint b)

file(WRITE "${WORK_DIR}/invalid.json" "{\"inputs\":[\"g.txt\"],\"github\":{\"token\":\"fake-secret-for-test\" broken}}")
execute_process(COMMAND "${EXECUTABLE}" validate --config "${WORK_DIR}/invalid.json"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT "${code}" STREQUAL "1" OR "${output}${error}" MATCHES "fake-secret-for-test")
    message(FATAL_ERROR "Invalid JSON must fail without exposing the token")
endif()

file(WRITE "${WORK_DIR}/g.txt" "1 2\n")
file(WRITE "${WORK_DIR}/tiny.json" "{\"inputs\":[\"g.txt\"],\"alpha_step\":1e-6}")
expect_cli(0 "preview limited to 20 tasks" validate --config "${WORK_DIR}/tiny.json")
expect_cli(0 "nodes=1 maximum_k=1" tree --config "${WORK_DIR}/tiny.json")
if(EXISTS "${WORK_DIR}/runs")
    message(FATAL_ERROR "validate must not create a working directory or output files")
endif()

file(MAKE_DIRECTORY "${WORK_DIR}/other")
file(WRITE "${WORK_DIR}/other/g.txt" "-8 42\n42 900\n900 -8\n")
file(WRITE "${WORK_DIR}/run.json" "{\"inputs\":[\"g.txt\",\"other/g.txt\"],\"alpha_step\":0.2,\"threads\":4,\"working_directory\":\"solutions\"}")
expect_cli(0 "unique_sizes=3" run --config "${WORK_DIR}/run.json")
file(READ "${WORK_DIR}/solutions/graph_0/g_sol.txt" edge_answer)
set(expected_edge "0.2 1 0 0\n0.4 1 0 0\n0.6 1 0 0\n0.8 1 0 0\n1 2 1 1\n1 2\n")
if(NOT edge_answer STREQUAL expected_edge)
    message(FATAL_ERROR "Wrong shared-r output: ${edge_answer}")
endif()
file(READ "${WORK_DIR}/solutions/graph_1/g_sol.txt" triangle_answer)
set(expected_triangle "0.2 1 0 0\n0.4 1 0 0\n0.6 1 0 0\n0.8 2 1 1\n-8 42\n1 3 2 3\n-8 42\n-8 900\n42 900\n")
if(NOT triangle_answer STREQUAL expected_triangle)
    message(FATAL_ERROR "Wrong triangle output: ${triangle_answer}")
endif()
expect_cli(0 "r=1 k=0 computed vertex=1" run --config "${WORK_DIR}/run.json")
file(READ "${WORK_DIR}/solutions/graph_0/g_sol.txt" rerun_answer)
if(NOT rerun_answer STREQUAL edge_answer)
    message(FATAL_ERROR "Repeated run must replace output without duplicate blocks")
endif()
file(WRITE "${WORK_DIR}/collision.json" "{\"inputs\":[\"g.txt\",\"solutions/graph_0/g_sol.txt\"],\"working_directory\":\"solutions\"}")
expect_cli(1 "must not overwrite" run --config "${WORK_DIR}/collision.json")
file(WRITE "${WORK_DIR}/blocked" "not a directory")
file(WRITE "${WORK_DIR}/blocked.json" "{\"inputs\":[\"g.txt\"],\"alpha_step\":1,\"working_directory\":\"blocked\"}")
expect_cli(1 "Error:" run --config "${WORK_DIR}/blocked.json")

file(WRITE "${WORK_DIR}/cycle.json" "{\"inputs\":[\"${SOURCE_DIR}/examples/cycle_triangle.txt\"],\"working_directory\":\"cycle-answers\"}")
expect_cli(0 "unique_sizes=9" run --config "${WORK_DIR}/cycle.json")
file(READ "${WORK_DIR}/cycle-answers/graph_0/cycle_triangle_sol.txt" cycle_answer)
if(NOT cycle_answer MATCHES "0.4 3 2 3\n70 80\n70 90\n80 90\n")
    message(FATAL_ERROR "Example solution did not select the triangle for r=3")
endif()

if(UNIX)
    file(MAKE_DIRECTORY "${WORK_DIR}/aliased/shared")
    file(REMOVE "${WORK_DIR}/aliased/graph_0" "${WORK_DIR}/aliased/graph_1")
    file(CREATE_LINK "${WORK_DIR}/aliased/shared" "${WORK_DIR}/aliased/graph_0" SYMBOLIC)
    file(CREATE_LINK "${WORK_DIR}/aliased/shared" "${WORK_DIR}/aliased/graph_1" SYMBOLIC)
    file(WRITE "${WORK_DIR}/aliased.json" "{\"inputs\":[\"g.txt\",\"other/g.txt\"],\"working_directory\":\"aliased\"}")
    expect_cli(1 "output paths must be distinct" run --config "${WORK_DIR}/aliased.json")
endif()

message(STATUS "CLI integration checks passed")
